# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-17 08:27
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SensorModule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('moduleName', models.CharField(max_length=250)),
                ('ipAddress', models.GenericIPAddressField()),
                ('sensorData', django.contrib.postgres.fields.jsonb.JSONField(db_index=True)),
                ('sensorReadingAvg', django.contrib.postgres.fields.jsonb.JSONField()),
                ('gpsData', django.contrib.postgres.fields.jsonb.JSONField()),
            ],
        ),
    ]
